import React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { useToast } from '@/hooks/use-toast';
import { useQuote } from '@/contexts/QuoteContext';
import { Loader2 } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';

// Phone number utilities
const formatAustralianPhone = (value: string): string => {
  const cleaned = value.replace(/\D/g, '');
  if (cleaned.length <= 4) return cleaned;
  if (cleaned.length <= 7) return `${cleaned.slice(0, 4)} ${cleaned.slice(4)}`;
  return `${cleaned.slice(0, 4)} ${cleaned.slice(4, 7)} ${cleaned.slice(7, 10)}`;
};

const isValidAustralianPhone = (phone: string): boolean => {
  const cleaned = phone.replace(/\D/g, '');
  return /^0[2-9]\d{8}$/.test(cleaned) || /^04\d{8}$/.test(cleaned);
};

const enhancedQuoteFormSchema = z.object({
  otName: z.string().min(2, 'Name must be at least 2 characters'),
  otEmail: z.string().email('Please enter a valid email address'),
  otPhone: z.string().refine(isValidAustralianPhone, {
    message: 'Please enter a valid Australian phone number',
  }),
  organization: z.string().optional(),
  fundingType: z.string().optional(),
  deliveryPostcode: z.string().optional(),
  notes: z.string().optional(),
});

type EnhancedQuoteFormData = z.infer<typeof enhancedQuoteFormSchema>;

interface EnhancedQuoteFormProps {
  onSuccess?: () => void;
}

const EnhancedQuoteForm: React.FC<EnhancedQuoteFormProps> = ({ onSuccess }) => {
  const { toast } = useToast();
  const { state, clearQuote } = useQuote();
  
  const form = useForm<EnhancedQuoteFormData>({
    resolver: zodResolver(enhancedQuoteFormSchema),
    defaultValues: {
      otName: '',
      otEmail: '',
      otPhone: '',
      organization: '',
      fundingType: undefined,
      deliveryPostcode: '',
      notes: '',
    },
  });

  const onSubmit = async (data: EnhancedQuoteFormData) => {
    if (state.items.length === 0) {
      toast({
        title: 'No items in quote',
        description: 'Please add some products to your quote before submitting.',
        variant: 'destructive',
      });
      return;
    }

    try {
      // Submit main quote
      const { data: quoteData, error: quoteError } = await supabase
        .from('quotes')
        .insert({
          ot_name: data.otName,
          ot_email: data.otEmail,
          ot_phone: data.otPhone,
          organization: data.organization || null,
          funding_type: data.fundingType || null,
          delivery_postcode: data.deliveryPostcode || null,
          notes: data.notes || null,
          total_items: state.items.reduce((sum, item) => sum + item.quantity, 0),
          ref_code: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (quoteError) throw quoteError;

      // Submit quote items
      const quoteItems = state.items.map(item => ({
        quote_id: quoteData.id,
        product_id: item.productId,
        quantity: item.quantity,
        line_notes: item.lineNotes || null,
        unit_price: item.unitPrice || null,
      }));

      const { error: itemsError } = await supabase
        .from('quote_items')
        .insert(quoteItems);

      if (itemsError) throw itemsError;

      toast({
        title: 'Quote submitted successfully!',
        description: `Your quote reference is: ${quoteData.ref_code}`,
      });

      // Clear the form and quote
      form.reset();
      clearQuote();
      onSuccess?.();

    } catch (error: any) {
      console.error('Error submitting quote:', error);
      toast({
        title: 'Error submitting quote',
        description: error.message || 'Please try again later.',
        variant: 'destructive',
      });
    }
  };

  const handlePhoneChange = (value: string, onChange: (value: string) => void) => {
    const formatted = formatAustralianPhone(value);
    onChange(formatted);
  };

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>Quote Request Details</CardTitle>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="otName"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>OT Name *</FormLabel>
                    <FormControl>
                      <Input placeholder="Your full name" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="otEmail"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Email Address *</FormLabel>
                    <FormControl>
                      <Input type="email" placeholder="your@email.com" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="otPhone"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Phone Number *</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="0412 345 678"
                        {...field}
                        onChange={(e) => handlePhoneChange(e.target.value, field.onChange)}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="organization"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Organization</FormLabel>
                    <FormControl>
                      <Input placeholder="Your organization" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="fundingType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Funding Type</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value || ""}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select funding type" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="ndis">NDIS</SelectItem>
                          <SelectItem value="dva">DVA</SelectItem>
                          <SelectItem value="private">Private</SelectItem>
                          <SelectItem value="insurance">Insurance</SelectItem>
                          <SelectItem value="other">Other</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

              <FormField
                control={form.control}
                name="deliveryPostcode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Delivery Postcode</FormLabel>
                    <FormControl>
                      <Input placeholder="2000" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="notes"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Additional Notes</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="Any additional requirements or information..."
                      className="min-h-[100px]"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="bg-muted p-4 rounded-lg">
              <h4 className="font-medium mb-2">Quote Summary</h4>
              <p className="text-sm text-muted-foreground">
                {state.items.length} items • {state.items.reduce((sum, item) => sum + item.quantity, 0)} total quantity
              </p>
            </div>

            <Button 
              type="submit" 
              className="w-full" 
              size="lg"
              disabled={form.formState.isSubmitting}
            >
              {form.formState.isSubmitting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Submitting Quote...
                </>
              ) : (
                'Submit Quote Request'
              )}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
};

export default EnhancedQuoteForm;