-- Long description: full clean rewrite for every IC333 variant
UPDATE public.products
SET description = E'The Icare IC333 is a homecare profiling bed built for clients who need full hi-lo and four-section adjustment but don''t want the bedroom to look like a ward. The upholstered surround and choice of fabric or vinyl finishes let it sit alongside normal bedroom furniture rather than overpower it.\n\nTwo lift actuators deliver a combined 12,000 N of lifting power, with unlimited under-bed clearance for hoist access and eight heavy-duty castors for stable repositioning. Backrest, knee break, hi-lo and tilt are all powered, with a lockable handset for safe carer use.\n\nSizes available\nLong Single: 2200 x 1160 x 340 mm\nKing Single: 2200 x 1160 x 340 mm\nLong Double: 2200 x 1400 x 340 mm\nQueen: 2200 x 1600 x 340 mm\nSplit Queen: 2200 x 1600 x 340 mm\n\nFinishes\nFabric (commercial-grade velvet feel): Mist, Noir, Onyx, Silver, Smoke, Stone\nVinyl (commercial-grade jacquard): Sand, Bison, Slate, Dove, Ebony\n\nWarranty\nSteel frame: 10 years. Actuators, control box, castors, handset and upholstery: 2 years.'
WHERE sku LIKE 'IC333%';

UPDATE public.products_categorized
SET description_long = E'The Icare IC333 is a homecare profiling bed built for clients who need full hi-lo and four-section adjustment but don''t want the bedroom to look like a ward. The upholstered surround and choice of fabric or vinyl finishes let it sit alongside normal bedroom furniture rather than overpower it.\n\nTwo lift actuators deliver a combined 12,000 N of lifting power, with unlimited under-bed clearance for hoist access and eight heavy-duty castors for stable repositioning. Backrest, knee break, hi-lo and tilt are all powered, with a lockable handset for safe carer use.\n\nSizes available\nLong Single: 2200 x 1160 x 340 mm\nKing Single: 2200 x 1160 x 340 mm\nLong Double: 2200 x 1400 x 340 mm\nQueen: 2200 x 1600 x 340 mm\nSplit Queen: 2200 x 1600 x 340 mm\n\nFinishes\nFabric (commercial-grade velvet feel): Mist, Noir, Onyx, Silver, Smoke, Stone\nVinyl (commercial-grade jacquard): Sand, Bison, Slate, Dove, Ebony\n\nWarranty\nSteel frame: 10 years. Actuators, control box, castors, handset and upholstery: 2 years.',
    description_short = 'A four-function homecare bed with hi-lo lift, dual 12,000 N actuators and a residential look, designed to replace a hospital bed without making the bedroom feel clinical.',
    description = E'The Icare IC333 is a homecare profiling bed built for clients who need full hi-lo and four-section adjustment but don''t want the bedroom to look like a ward. The upholstered surround and choice of fabric or vinyl finishes let it sit alongside normal bedroom furniture rather than overpower it.\n\nTwo lift actuators deliver a combined 12,000 N of lifting power, with unlimited under-bed clearance for hoist access and eight heavy-duty castors for stable repositioning. Backrest, knee break, hi-lo and tilt are all powered, with a lockable handset for safe carer use.\n\nSizes available\nLong Single: 2200 x 1160 x 340 mm\nKing Single: 2200 x 1160 x 340 mm\nLong Double: 2200 x 1400 x 340 mm\nQueen: 2200 x 1600 x 340 mm\nSplit Queen: 2200 x 1600 x 340 mm\n\nFinishes\nFabric (commercial-grade velvet feel): Mist, Noir, Onyx, Silver, Smoke, Stone\nVinyl (commercial-grade jacquard): Sand, Bison, Slate, Dove, Ebony\n\nWarranty\nSteel frame: 10 years. Actuators, control box, castors, handset and upholstery: 2 years.'
WHERE sku LIKE 'IC333%';