// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgapzokhebqefasfznxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnYXB6b2toZWJxZWZhc2Z6bnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODM0MjcsImV4cCI6MjA3MDA1OTQyN30.MlWd9ce0-XDXv72HIxlwPZtV8pnxhr0hWinZDv2Ut_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});